### PR TITLE
loading models from 'models/TaggerOnnx'

### PR DESCRIPTION
**Pull request by ZZ250-zZ**
Prioritize loading models from directory 'models/TaggerOnnx'

### CODE REVIEW

**Comment by picobyte** [comment]
This is not fixing anything. Just use the environment variable as specified in the huggingface load api docs, if you don't want to load from huggingface.

**Comment by ZZ250-zZ** [comment]
> This is not fixing anything. Just use the environment variable as specified in the huggingface load api docs, if you don't want to load from huggingface.

- I downloaded the model to `sd-webui\models\TaggerOnnx` in advance. But, when running WD14, it loads the local model but still tries to download from huggingface.
```
sd-webui\models\TaggerOnnx
├── wd14-vit.v2
│   ├── model.onnx
│   └── selected_tags.csv
└── wd-v1-4-moat-tagger.v2
    ├── model.onnx
    └── selected_tags.csv
```
- The following code in `interrogator.py` is used to distinguish whether the model is scanned locally or downloaded from huggingface, but `self.is_hf` is always `true` for local models.

```
   def download(self) -> None:
        mdir = Path(shared.models_path, 'interrogators')
        if self.is_hf:
            cache = getattr(shared.opts, 'tagger_hf_cache_dir', Its.hf_cache)
            print(f"Loading {self.name} model file from {self.repo_id}, "
                  f"{self.model_path}")

            model_path = hf_hub_download(
                repo_id=self.repo_id,
                filename=self.model_path,
                cache_dir=cache)
            tags_path = hf_hub_download(
                repo_id=self.repo_id,
                filename=self.tags_path,
                cache_dir=cache)
        else:
            model_path = self.local_model
            tags_path = self.local_tags

    return sorted(interrogators.keys())
```

**Comment by picobyte** [comment]
[HF_HUB_OFFLINE](https://huggingface.co/docs/huggingface_hub/package_reference/environment_variables#hfhuboffline)=1 disables the download. so `export HF_HUB_OFFLINE=1` if on Linux, mac or os/x, or something like `HF_HUB_OFFLINE=1 ./webui`, not sure exactly how this is done in windows, but you can also in python do this:
```
import os
os.environ["HF_HUB_OFFLINE"] = "1"
```

There is already a long open issue about this, btw.

**Comment by ZZ250-zZ** [comment]
> [HF_HUB_OFFLINE](https://huggingface.co/docs/huggingface_hub/package_reference/environment_variables#hfhuboffline)=1 disables the download. so `export HF_HUB_OFFLINE=1` if on Linux, mac or os/x, or something like `HF_HUB_OFFLINE=1 ./webui`, not sure exactly how this is done in windows, but you can also in python do this:
> 
> ```
> import os
> os.environ["HF_HUB_OFFLINE"] = "1"
> ```
> 
> There is already a long open issue about this, btw.

I misunderstood. Thank you very much for your patient answer.

**Pull request closed without merging**
